### ISSUE TITLE
Been having lots of problems since Lightwave ?did something as they are now offering other services so don't know if they've changed code.

Radiators are not reporting their position. Seems can still send commands but won't tell me what position they are.

### ISSUE THREAD

**Issue by ianphillpott** [bigbadblunt/homeassistant-lightwave2#41] opened 2021-09-26 20:23 UTC

**Comment by bigbadblunt** [comment] 2021-09-26 20:50
Hi @ianphillpott , can you turn on logging, and reperform the action you're having trouble with please? Please also let me know what behaviour you expect (I don't have any TRVs so I'm not sure how they operate and what you expect).

To enable additional logging, add the following to configuration.yaml

logger:
  default: warning
  logs:
    lightwave2.lightwave2: debug
    custom_components.lightwave2: debug

**Comment by ianphillpott** [comment] 2021-09-26 21:11
I shall try and sort on Wednesday as likely have some time to sort.

**Comment by ianphillpott** [comment] 2021-09-29 10:37
This is the error showing in the log.

Logger: homeassistant.config_entries
Source: custom_components/lightwave2/__init__.py:111
Integration: Lightwave v2 (Smart Series) custom component (documentation)
First occurred: 11:33:03 AM (1 occurrences)
Last logged: 11:33:03 AM

Error setting up entry i*************t@gmail.com for lightwave2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/lightwave2/__init__.py", line 111, in async_setup_entry
    await link.async_get_hierarchy()
  File "/usr/local/lib/python3.9/site-packages/lightwave2/lightwave2.py", line 570, in async_get_hierarchy
    await self.async_update_featureset_states()
  File "/usr/local/lib/python3.9/site-packages/lightwave2/lightwave2.py", line 615, in async_update_featureset_states
    req = await self._async_postrequest("features/read", body)
  File "/usr/local/lib/python3.9/site-packages/lightwave2/lightwave2.py", line 526, in _async_postrequest
    _LOGGER.debug("async_postrequest: Received API response {} {} {}".format(req.status, await req.text(), await req.json()))
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1097, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://publicapi.lightwaverf.com/v1/features/read')

Just going to add the logging commands and try some actions.

**Comment by ianphillpott** [comment] 2021-09-29 11:01
It is now doing basically nothing - can't get any of the integration to work! 
[LW Debug Log.txt](https://github.com/bigbadblunt/homeassistant-lightwave2/files/7251265/LW.Debug.Log.txt)

**Comment by bigbadblunt** [comment] 2021-09-29 11:38
Thanks @ianphillpott 

Looks like you're using the "public API" setting. Can you turn this off (in the integrations page of HA, you should be able to change the settings for this component). Then restart and let me know what happens.

**Comment by ianphillpott** [comment] 2021-09-29 14:36
Ooo things seem to be working. Will do some testing and let you know! Odd how that managed to turn on randomly!

**Comment by mjsblume** [comment] 2021-10-01 09:05
Curious to know why the public API breaks it?

**Comment by bigbadblunt** [comment] 2021-10-01 09:17
Not sure, I will have a look when I have time. I've had a reasonable number of issues in the past with stability of the public API.

**Comment by bigbadblunt** [comment] 2021-10-02 17:26
I can't reproduce the problem with the public API code, but if the normal setup is worked then I'm not inclined to keep investigating. I've added some more debugging code to the next release, so if this kind of thing happens again it'll be easier to track down.

@ianphillpott let me know if it's working now and you're happy to close this.

**Comment by bigbadblunt** [comment] 2021-11-06 09:45
I'm going to assume this is working now. Also the public API seems to be fixed now - I'm not sure if anyone is using it, and I'd still recommend not doing so.

**Closed by bigbadblunt** 2021-11-06 09:45 UTC
