### ISSUE TITLE
Functionality question...

### ISSUE THREAD

**Issue by stroppygoblin** [bigbadblunt/homeassistant-lightwave2#106] opened 2022-12-06 00:47 UTC
Functionality question...
I have a Smart Dimmer switch set to ignore input channel, this is because I want the following functionality:

Single click On - Turn on the main light the switch is wired to
Double Click On - Turn on some table lamps (Hue Bulbs) but NOT the main light

Single click Off - Turn off the main light the switch is wired to
Double Click Off - Turn off some table lamps (Hue Bulbs) but NOT the main light

All of this works perfectly, but what I'd like to is get back the ability to brighten and dim the main light. Is this possible with this configuration?

**Comment by bigbadblunt** [comment] 2022-12-06 18:38
Not sure - seems like you have two options.

1) link triple clicks to changes in brightness in steps
2) detect "long press down" and "long press release" events and continuously change the brightness

I'm not very familiar with automations to advise on how to do the latter.

**Comment by bigbadblunt** [comment] 2022-12-30 09:12
Closing as not a bug. Let me know if you need more help.

**Closed by bigbadblunt** 2022-12-30 09:12 UTC
