### ISSUE TITLE
Received message for unregistered webhook

### ISSUE THREAD

**Issue by robcos** [bigbadblunt/homeassistant-lightwave2#76] opened 2022-05-04 12:35 UTC
Not sure if this is really an issue but I thought it was worth reporting it.
My logs are full with _unregistered webhook_ messages attributable to lighwaverf

2022-05-04 13:34:41 DEBUG (MainThread) [lightwave2.lightwave2] consumer_handler: Received WSMessage(type=<WSMsgType.TEXT: 1>, data='{"version":1,"senderId":"1.ip=10=192=22=252*eu=west=1*compute*internal=92325","transactionId":4977883,"direction":"notification","class":"feature","operation":"event","items":[{"payload":{"featureId":"5f4e7a036128780da048dcb9-38-3157348997+1","deviceId":2,"type":"switch","channel":2,"writable":true,"stateless":false,"virtual":false,"value":1,"status":"ok"},"success":true,"itemId":74}]}', extra='')
2022-05-04 13:34:41 DEBUG (MainThread) [lightwave2.lightwave2] consumer_handler: Event received (5f4e7a036128780da048dcb9-38-3157348997+1 <lightwave2.lightwave2.LWRFFeature object at 0x7fb1b3ab3610> 1), calling callbacks ['async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback']
2022-05-04 13:34:41 DEBUG (MainThread) [lightwave2.lightwave2] consumer_handler: Starting consumer handler
2022-05-04 13:34:41 DEBUG (MainThread) [lightwave2.lightwave2] consumer_handler: Received WSMessage(type=<WSMsgType.TEXT: 1>, data='{"version":1,"senderId":"1.ip=10=192=22=252*eu=west=1*compute*internal=92325","transactionId":4977884,"direction":"notification","class":"feature","operation":"event","items":[{"payload":{"featureId":"5f4e7a036128780da048dcb9-315-3157348997+1","deviceId":2,"type":"uiButtonPair","channel":2,"writable":true,"stateless":true,"virtual":false,"value":257,"status":"ok"},"success":true,"itemId":75}]}', extra='')
2022-05-04 13:34:41 DEBUG (MainThread) [lightwave2.lightwave2] consumer_handler: Event received (5f4e7a036128780da048dcb9-315-3157348997+1 <lightwave2.lightwave2.LWRFFeature object at 0x7fb1b3ab3880> 257), calling callbacks ['async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback']
2022-05-04 13:34:41 DEBUG (MainThread) [custom_components.lightwave2.light] Button (light) press event: light.secondfloor_studyroberto_desk_wall 257
2022-05-04 13:34:41 DEBUG (MainThread) [lightwave2.lightwave2] consumer_handler: Starting consumer handler
2022-05-04 13:34:41 DEBUG (MainThread) [homeassistant.components.webhook] Handling webhook POST payload for a1d39b199b94f9ff888931f94909d98b01a132fd952eee656f3b3b6f8a2fd777
2022-05-04 13:34:41 INFO (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook a1d39b199b94f9ff888931f94909d98b01a132fd952eee656f3b3b6f8a2fd777 from 34.242.166.156
2022-05-04 13:34:41 DEBUG (MainThread) [homeassistant.components.webhook] b'{"id":"hass5f4e7a036128780da048dcb9-38-3157348997P1","userId":"f'
2022-05-04 13:34:41 DEBUG (MainThread) [homeassistant.components.webhook] Handling webhook POST payload for 15d8c7a2f056c9e56082c539973c715daf834717fe318c92d2b8f18fe9a88ebe
2022-05-04 13:34:41 INFO (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 15d8c7a2f056c9e56082c539973c715daf834717fe318c92d2b8f18fe9a88ebe from 34.242.166.156
2022-05-04 13:34:41 DEBUG (MainThread) [homeassistant.components.webhook] b'{"id":"lightwave_webhook4","userId":"f89f705d-987c-45f2-9828-a60'
2022-05-04 13:34:41 DEBUG (MainThread) [homeassistant.components.webhook] Handling webhook POST payload for 15d8c7a2f056c9e56082c539973c715daf834717fe318c92d2b8f18fe9a88ebe
2022-05-04 13:34:41 INFO (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 15d8c7a2f056c9e56082c539973c715daf834717fe318c92d2b8f18fe9a88ebe from 34.242.166.156
2022-05-04 13:34:41 DEBUG (MainThread) [homeassistant.components.webhook] b'{"id":"lightwave_webhook3","userId":"f89f705d-987c-45f2-9828-a60'

**Comment by bigbadblunt** [comment] 2022-05-07 09:57
Definitely nothing to worry about, these are just webhooks from a previous connection. It's a bit untidy though, I should do something to fix it.

**Comment by bigbadblunt** [comment] 2022-05-15 13:05
I've added a service call `lightwave2.whdelete` which you can call to tidy this up if it bothers you. You'll need to switch to the public API before this will work.

**Comment by robcos** [comment] 2022-05-15 13:31
I actually have a bigger problem which is why I was looking into this.
My multiple clicks stop working every day or so. I can't see the events in nodered nor in the developer console in HA.
Rebooting HA fixes the problem. I have excluded reception issues (they show up in the LW app). What can I do to debug it?

**Comment by bigbadblunt** [comment] 2022-05-15 13:32
Is this the same issue as #69?

**Comment by robcos** [comment] 2022-05-15 20:19
Most likely!

**Comment by bigbadblunt** [comment] 2022-10-22 05:50
Closing as the webhook issue is fixed and the remaining issue is a duplicate of #69

**Closed by bigbadblunt** 2022-10-22 05:50 UTC
